#!/bin/sh

set -e

INPROG=$1
DIR="./output/"
PROG="$(basename ${INPROG})"
PROGNAME="${PROG%.*}"
ASMFILE="${DIR}${PROGNAME}.S"
OBJFILE="${DIR}${PROGNAME}.o"
RUNTIMEOBJ="${DIR}runtime.o"

mkdir -p $DIR
dune exec bin/print_x86.exe $1 > $ASMFILE
nasm -f elf64 -o $OBJFILE $ASMFILE
gcc -c runtime/runtime.c -o $RUNTIMEOBJ
gcc -o "${DIR}$PROGNAME" $OBJFILE $RUNTIMEOBJ
